name: final_project_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^12.0.0
  json_annotation: ^4.9.0
  provider: ^6.1.2
  google_maps_flutter: ^2.6.1
  csv: ^6.0.0
  http: ^1.2.1
  logger: ^2.3.0
  url_launcher: ^6.2.6
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/